---
- name: start nginx
  become: yes
  service:
    name: nginx
    state: started


- name: restart nginx
  service: name=nginx state=restarted

- name: validate nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: false

- name: reload nginx
  service: name=nginx state=reloaded
