- name: update web, nfs servers
  hosts: webservers, nfs
  remote_user: ec2-user
  become: yes
  become_user: root
  gather_facts: False
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest

- name: update LB server
  hosts: lb,db 
  remote_user: ubuntu
  become: yes
  become_user: root
  gather_facts: False
  tasks:
    # - name: Update apt repo
    #   apt: 
        
    #     update_cache: yes
    #     cache_valid_time: 3600

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest