---
- hosts: all
- name: Include dynamic variables 
  tasks:
  import_playbook: ../static-assignments/common.yaml 
  include: ../dynamic-assignments/env-vars.yaml
    tags:
      - always

- name: import database file
  import_playbook: ../static-assignments/db.yaml

- hosts: lb
- name: Loadbalancers assignment
    import_playbook: ../static-assignments/loadbalancers.yaml
    when: load_balancer_is_required
